(function(){function s(b){var a=!1;return function(){if(a)throw Error("Callback was already called.");a=!0;b.apply(n,arguments)}}var d={},n,t;n=this;null!=n&&(t=n.async);d.noConflict=function(){n.async=t;return d};var j=function(b,a){if(b.forEach)return b.forEach(a);for(var c=0;b.length>c;c+=1)a(b[c],c,b)},l=function(b,a){if(b.map)return b.map(a);var c=[];j(b,function(b,e,h){c.push(a(b,e,h))});return c},y=function(b,a,c){if(b.reduce)return b.reduce(a,c);j(b,function(b,e,h){c=a(c,b,e,h)});return c},
p=function(b){if(Object.keys)return Object.keys(b);var a=[],c;for(c in b)b.hasOwnProperty(c)&&a.push(c);return a};d.nextTick="undefined"!=typeof process&&process.nextTick?process.nextTick:"function"==typeof setImmediate?function(b){setImmediate(b)}:function(b){setTimeout(b,0)};d.each=function(b,a,c){c=c||function(){};if(!b.length)return c();var f=0;j(b,function(e){a(e,s(function(a){a?(c(a),c=function(){}):(f+=1,f>=b.length&&c(null))}))})};d.forEach=d.each;d.eachSeries=function(b,a,c){c=c||function(){};
if(!b.length)return c();var f=0,e=function(){var h=!0;a(b[f],function(a){a?(c(a),c=function(){}):(f+=1,f>=b.length?c(null):h?d.nextTick(e):e())});h=!1};e()};d.forEachSeries=d.eachSeries;d.eachLimit=function(b,a,c,f){r(a).apply(null,[b,c,f])};d.forEachLimit=d.eachLimit;var r=function(b){return function(a,c,f){f=f||function(){};if(!a.length||0>=b)return f();var e=0,h=0,d=0;(function k(){if(e>=a.length)return f();for(;b>d&&a.length>h;)h+=1,d+=1,c(a[h-1],function(b){b?(f(b),f=function(){}):(e+=1,d-=1,
e>=a.length?f():k())})})()}},m=function(b){return function(){var a=Array.prototype.slice.call(arguments);return b.apply(null,[d.each].concat(a))}},v=function(b,a){return function(){var c=Array.prototype.slice.call(arguments);return a.apply(null,[r(b)].concat(c))}},o=function(b){return function(){var a=Array.prototype.slice.call(arguments);return b.apply(null,[d.eachSeries].concat(a))}},q=function(b,a,c,f){var e=[],a=l(a,function(a,b){return{index:b,value:a}});b(a,function(a,b){c(a.value,function(c,
f){e[a.index]=f;b(c)})},function(a){f(a,e)})};d.map=m(q);d.mapSeries=o(q);d.mapLimit=function(b,a,c,f){return v(a,q)(b,c,f)};d.reduce=function(b,a,c,f){d.eachSeries(b,function(b,f){c(a,b,function(b,c){a=c;f(b)})},function(b){f(b,a)})};d.inject=d.reduce;d.foldl=d.reduce;d.reduceRight=function(b,a,c,f){b=l(b,function(a){return a}).reverse();d.reduce(b,a,c,f)};d.foldr=d.reduceRight;var g=function(b,a,c,f){var e=[],a=l(a,function(a,b){return{index:b,value:a}});b(a,function(a,b){c(a.value,function(c){c&&
e.push(a);b()})},function(){f(l(e.sort(function(a,b){return a.index-b.index}),function(a){return a.value}))})};d.filter=m(g);d.filterSeries=o(g);d.select=d.filter;d.selectSeries=d.filterSeries;g=function(b,a,c,f){var e=[],a=l(a,function(a,b){return{index:b,value:a}});b(a,function(a,b){c(a.value,function(c){c||e.push(a);b()})},function(){f(l(e.sort(function(a,b){return a.index-b.index}),function(a){return a.value}))})};d.reject=m(g);d.rejectSeries=o(g);g=function(b,a,c,f){b(a,function(a,b){c(a,function(c){c?
(f(a),f=function(){}):b()})},function(){f()})};d.detect=m(g);d.detectSeries=o(g);d.some=function(b,a,c){d.each(b,function(b,e){a(b,function(a){a&&(c(!0),c=function(){});e()})},function(){c(!1)})};d.any=d.some;d.every=function(b,a,c){d.each(b,function(b,e){a(b,function(a){a||(c(!1),c=function(){});e()})},function(){c(!0)})};d.all=d.every;d.sortBy=function(b,a,c){d.map(b,function(b,c){a(b,function(a,d){a?c(a):c(null,{value:b,criteria:d})})},function(a,b){if(a)return c(a);c(null,l(b.sort(function(a,
b){var c=a.criteria,f=b.criteria;return f>c?-1:c>f?1:0}),function(a){return a.value}))})};d.auto=function(b,a){var a=a||function(){},c=p(b);if(!c.length)return a(null);var f={},e=[],h=function(a){e.unshift(a)},i=function(){j(e.slice(0),function(a){a()})};h(function(){p(f).length===c.length&&(a(null,f),a=function(){})});j(c,function(c){var k=b[c]instanceof Function?[b[c]]:b[c],u=function(b){if(b)a(b),a=function(){};else{var e=Array.prototype.slice.call(arguments,1);1>=e.length&&(e=e[0]);f[c]=e;d.nextTick(i)}},
g=k.slice(0,Math.abs(k.length-1))||[],j=function(){return y(g,function(a,b){return a&&f.hasOwnProperty(b)},!0)&&!f.hasOwnProperty(c)};if(j())k[k.length-1](u,f);else{var l=function(){if(j()){for(var a=l,b=0;e.length>b;b+=1)if(e[b]===a){e.splice(b,1);break}k[k.length-1](u,f)}};h(l)}})};d.waterfall=function(b,a){a=a||function(){};if(!b.length)return a();var c=function(b){return function(e){if(e)a.apply(null,arguments),a=function(){};else{var h=Array.prototype.slice.call(arguments,1),i=b.next();i?h.push(c(i)):
h.push(a);d.nextTick(function(){b.apply(null,h)})}}};c(d.iterator(b))()};var x=function(b,a,c){c=c||function(){};if(a.constructor===Array)b.map(a,function(a,b){a&&a(function(a){var c=Array.prototype.slice.call(arguments,1);1>=c.length&&(c=c[0]);b.call(null,a,c)})},c);else{var f={};b.each(p(a),function(b,c){a[b](function(a){var d=Array.prototype.slice.call(arguments,1);1>=d.length&&(d=d[0]);f[b]=d;c(a)})},function(a){c(a,f)})}};d.parallel=function(b,a){x({map:d.map,each:d.each},b,a)};d.parallelLimit=
function(b,a,c){x({map:v(a,q),each:r(a)},b,c)};d.series=function(b,a){a=a||function(){};if(b.constructor===Array)d.mapSeries(b,function(a,b){a&&a(function(a){var c=Array.prototype.slice.call(arguments,1);1>=c.length&&(c=c[0]);b.call(null,a,c)})},a);else{var c={};d.eachSeries(p(b),function(a,d){b[a](function(b){var i=Array.prototype.slice.call(arguments,1);1>=i.length&&(i=i[0]);c[a]=i;d(b)})},function(b){a(b,c)})}};d.iterator=function(b){var a=function(c){var d=function(){b.length&&b[c].apply(null,
arguments);return d.next()};d.next=function(){return b.length-1>c?a(c+1):null};return d};return a(0)};d.apply=function(b){var a=Array.prototype.slice.call(arguments,1);return function(){return b.apply(null,a.concat(Array.prototype.slice.call(arguments)))}};g=function(b,a,c,d){var e=[];b(a,function(a,b){c(a,function(a,c){e=e.concat(c||[]);b(a)})},function(a){d(a,e)})};d.concat=m(g);d.concatSeries=o(g);d.whilst=function(b,a,c){if(b()){var f=!0;a(function(e){if(e)return c(e);f?d.nextTick(function(){d.whilst(b,
a,c)}):d.whilst(b,a,c)});f=!1}else c()};d.doWhilst=function(b,a,c){var f=!0;b(function(e){if(e)return c(e);a()?f?d.nextTick(function(){d.doWhilst(b,a,c)}):d.doWhilst(b,a,c):c()});f=!1};d.until=function(b,a,c){if(b())c();else{var f=!0;a(function(e){if(e)return c(e);f?d.nextTick(function(){d.until(b,a,c)}):d.until(b,a,c)});f=!1}};d.doUntil=function(b,a,c){var f=!0;b(function(e){if(e)return c(e);a()?c():f?d.nextTick(function(){d.doUntil(b,a,c)}):d.doUntil(b,a,c)});f=!1};d.queue=function(b,a){function c(b,
c,e,f){c.constructor!==Array&&(c=[c]);j(c,function(c){c={data:c,callback:"function"==typeof f?f:null};e?b.tasks.unshift(c):b.tasks.push(c);b.saturated&&b.tasks.length===a&&b.saturated();d.nextTick(b.process)})}var f=0,e={tasks:[],concurrency:a,saturated:null,empty:null,drain:null,push:function(a,b){c(e,a,!1,b)},unshift:function(a,b){c(e,a,!0,b)},process:function(){if(e.concurrency>f&&e.tasks.length){var a=e.tasks.shift();e.empty&&0===e.tasks.length&&e.empty();f+=1;var c=!0,w=function(){f-=1;a.callback&&
a.callback.apply(a,arguments);e.drain&&0===e.tasks.length+f&&e.drain();e.process()},k=s(function(){var a=arguments;c?d.nextTick(function(){w.apply(null,a)}):w.apply(null,arguments)});b(a.data,k);c=!1}},length:function(){return e.tasks.length},running:function(){return f}};return e};d.cargo=function(b,a){var c=!1,f=[],e={tasks:f,payload:a,saturated:null,empty:null,drain:null,push:function(b,c){b.constructor!==Array&&(b=[b]);j(b,function(b){f.push({data:b,callback:"function"==typeof c?c:null});e.saturated&&
f.length===a&&e.saturated()});d.nextTick(e.process)},process:function i(){if(!c)if(0===f.length)e.drain&&e.drain();else{var d="number"==typeof a?f.splice(0,a):f.splice(0),k=l(d,function(a){return a.data});e.empty&&e.empty();c=!0;b(k,function(){c=!1;var a=arguments;j(d,function(b){b.callback&&b.callback.apply(null,a)});i()})}},length:function(){return f.length},running:function(){return c}};return e};m=function(b){return function(a){var c=Array.prototype.slice.call(arguments,1);a.apply(null,c.concat([function(a){var c=
Array.prototype.slice.call(arguments,1);"undefined"!=typeof console&&(a?console.error&&console.error(a):console[b]&&j(c,function(a){console[b](a)}))}]))}};d.log=m("log");d.dir=m("dir");d.memoize=function(b,a){var c={},d={},a=a||function(a){return a},e=function(){var e=Array.prototype.slice.call(arguments),i=e.pop(),g=a.apply(null,e);g in c?i.apply(null,c[g]):g in d?d[g].push(i):(d[g]=[i],b.apply(null,e.concat([function(){c[g]=arguments;var a=d[g];delete d[g];for(var b=0,e=a.length;e>b;b++)a[b].apply(null,
arguments)}])))};e.memo=c;e.unmemoized=b;return e};d.unmemoize=function(b){return function(){return(b.unmemoized||b).apply(null,arguments)}};d.times=function(b,a,c){for(var f=[],e=0;b>e;e++)f.push(e);return d.map(f,a,c)};d.timesSeries=function(b,a,c){for(var f=[],e=0;b>e;e++)f.push(e);return d.mapSeries(f,a,c)};d.compose=function(){var b=Array.prototype.reverse.call(arguments);return function(){var a=this,c=Array.prototype.slice.call(arguments),f=c.pop();d.reduce(b,c,function(b,c,d){c.apply(a,b.concat([function(){var a=
arguments[0],b=Array.prototype.slice.call(arguments,1);d(a,b)}]))},function(b,c){f.apply(a,[b].concat(c))})}};"undefined"!=typeof define&&define.amd?define([],function(){return d}):"undefined"!=typeof module&&module.exports?module.exports=d:n.async=d})();
